[SS-39] migrate to fast api
Star-Sync/ss-server pull request #6
Opened 2024-11-07 21:07 UTC by FTadros

![image](https://github.com/user-attachments/assets/ba91deb9-d73c-4fb3-b315-63f9deedbefd)

2024-11-07 21:09 UTC, FTadros commented
![image](https://github.com/user-attachments/assets/788f99e2-f66f-4885-a3ae-038cf86b52c5)
😄

2024-11-07 21:14 UTC, FTadros commented on app/tests/test_gs_mock.py
> +    # technically, we dont need to test this
=) no longer need to validate all this, fastAPI handles so much of the validation

2024-11-07 21:14 UTC, FTadros commented on app/tests/test_gs_mock.py
> +    payload = {
it even does the conversion on different date formats, as the validation is done by the `dattetime` class rather than me picking a random string

2024-11-07 21:14 UTC, FTadros commented on app/routers/gs_mock.py
> +    if start is None or end is None or delta is None:
this should never happen due to fastapi handling the edge case for us

2024-11-07 21:41 UTC, dzinkiv approved these changes

2024-11-08 15:56 UTC, dzinkiv commented
@FTadros What is `pyproject.toml` file? If it's needed, do we remove Flask from dependencies list?

2024-11-08 16:00 UTC, dzinkiv requested changes
Could you please update README file to show how to run app with now new Fastapi framework?

2024-11-08 16:25 UTC, FTadros commented
> @FTadros What is `pyproject.toml` file? If it's needed, do we remove Flask from dependencies list?

https://packaging.python.org/en/latest/guides/writing-pyproject-toml/

python's attempt at consolidating all config files into one, could also move the `pytest` config in there aswell

2024-11-08 22:07 UTC, dzinkiv approved these changes
Looks great!

2024-11-08 22:09 UTC, merged